AWSTemplateFormatVersion: 2010-09-09
Description:
  Kittens Carousel is a static website application deployed 
  with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.
Resources:
   OguzCFNInstance:
     Type: AWS::EC2::Instance
     Properties:
       ImageId: ami-0a8b4cd432b1c3063
       InstanceType: t2.micro
       KeyName: firstkey
       SecurityGroups:
         - cfn-sec-group
       Tags:
         - Key: Name
           Value: Cfn-Instance

